#!/usr/bin/env bash
# Render Salt formula from JSON spec (AI → JSON → this script → formula).
# Requires: bash, jq
#
# Usage:
#   ./render_formula.sh --spec ./spec.json [--out ./dist]
#
set -euo pipefail

SPEC=""
OUT_DIR="."

usage() {
  cat <<'USAGE'
Usage: render_formula.sh --spec <spec.json> [--out <dir>]

Reads formula JSON spec and creates <name>-formula/ with full file contents.
Requires: jq

Example:
  ./render_formula.sh --spec examples/specs/nginx.json --out /tmp
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --spec) SPEC="$2"; shift 2 ;;
    --out) OUT_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "${SPEC}" || ! -f "${SPEC}" ]]; then
  echo "ERROR: --spec file required" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required (brew install jq / apt install jq)" >&2
  exit 1
fi

if ! jq empty "${SPEC}" 2>/dev/null; then
  echo "ERROR: invalid JSON: ${SPEC}" >&2
  exit 1
fi

NAME="$(jq -r '.name // empty' "${SPEC}")"
TOP="$(jq -r '.top_level_dir // .name // empty' "${SPEC}")"
KIND="$(jq -r '.formula_kind // "package"' "${SPEC}")"
WITH_REPO="$(jq -r '(.with_repo // false) | tostring' "${SPEC}")"
RELEASE="$(jq -r '.release // 1' "${SPEC}")"
VERSION="$(date +%Y%m)"

case "${KIND}" in
  package|security-baseline) ;;
  *)
    echo "ERROR: unsupported formula_kind: ${KIND} (package|security-baseline)" >&2
    exit 1
    ;;
esac

if [[ -z "${NAME}" || -z "${TOP}" ]]; then
  echo "ERROR: name / top_level_dir required" >&2
  exit 1
fi

if [[ ! "${NAME}" =~ ^[a-zA-Z0-9_-]+$ || ! "${TOP}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "ERROR: name/top_level_dir must match [a-zA-Z0-9_-]+" >&2
  exit 1
fi

OS_COUNT="$(jq -r '(.os // []) | length' "${SPEC}")"
OSF_COUNT="$(jq -r '(.os_family // []) | length' "${SPEC}")"
if [[ "${OS_COUNT}" -lt 1 || "${OSF_COUNT}" -lt 1 ]]; then
  echo "ERROR: os and os_family must be non-empty arrays" >&2
  exit 1
fi

FORMULA_DIR="${OUT_DIR}/${TOP}-formula"
mkdir -p "${FORMULA_DIR}"

write_file() {
  local rel="$1"
  local target="${FORMULA_DIR}/${rel}"
  mkdir -p "$(dirname "${target}")"
  cat > "${target}"
}

fail_if_empty() {
  local f="$1"
  [[ -s "${f}" ]] || { echo "ERROR: empty file: ${f}" >&2; exit 1; }
}

# --- FORMULA ---
write_file "FORMULA" <<EOF
name: ${NAME}
os:
$(jq -r '.os[] | "  - \(.)"' "${SPEC}")
os_family:
$(jq -r '.os_family[] | "  - \(.)"' "${SPEC}")
version: ${VERSION}
release: ${RELEASE}
summary: $(jq -r '.summary // "Autogenerated formula" | @json' "${SPEC}")
description: $(jq -r '.description // .summary // "Autogenerated Salt formula" | @json' "${SPEC}")
top_level_dir: ${TOP}
EOF

# --- pillar.example (JSON under lookup is valid and readable) ---
write_file "pillar.example" <<EOF
${NAME}:
  # Override map.jinja defaults
  lookup: $(jq -c '.pillar_lookup // {}' "${SPEC}")
EOF

# --- map.jinja ---
write_file "${TOP}/map.jinja" <<EOF
{# -*- coding: utf-8 -*- #}
{# vim: ft=jinja #}
{# Generated by render_formula.sh from JSON spec #}
{% set mapdata = salt['grains.filter_by']($(jq -c '.map_defaults // {"default":{}}' "${SPEC}"), merge=salt['pillar.get']('${NAME}:lookup'), base='default') %}
EOF

# --- formula body by kind ---
if [[ "${KIND}" == "security-baseline" ]]; then

write_file "${TOP}/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Meta-state: apply Linux security baseline

{#- Get the `tplroot` from `tpldir` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

include:
{%- if sb.enable_packages %}
  - .packages
{%- endif %}
{%- if sb.enable_ssh %}
  - .ssh
{%- endif %}
{%- if sb.enable_sysctl %}
  - .sysctl
{%- endif %}
{%- if sb.enable_services %}
  - .services
{%- endif %}
EOF

write_file "${TOP}/clean.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Meta-state: rollback security baseline (reverse order)

{#- Get the `tplroot` from `tpldir` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

include:
{%- if sb.enable_services %}
  - .services.clean
{%- endif %}
{%- if sb.enable_sysctl %}
  - .sysctl.clean
{%- endif %}
{%- if sb.enable_ssh %}
  - .ssh.clean
{%- endif %}
{%- if sb.enable_packages %}
  - .packages.clean
{%- endif %}
EOF

write_file "${TOP}/check.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Meta-state: compliance check (no remediation)

{#- Get the `tplroot` from `tpldir` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

include:
{%- if sb.enable_ssh %}
  - .ssh.check
{%- endif %}
{%- if sb.enable_sysctl %}
  - .sysctl.check
{%- endif %}
{%- if sb.enable_services %}
  - .services.check
{%- endif %}
{%- if sb.enable_packages %}
  - .packages.check
{%- endif %}
EOF

write_file "${TOP}/files/sshd-security-baseline.conf.j2" <<EOF
# Managed by Osmax formula ${NAME}. Do not edit manually.
# {{ salt['pillar.get']('${NAME}:version_id', 'n/a') }}

Protocol {{ ssh.protocol }}
PermitRootLogin {{ ssh.permit_root_login }}
PasswordAuthentication {{ ssh.password_authentication }}
PubkeyAuthentication {{ ssh.pubkey_authentication }}
ChallengeResponseAuthentication {{ ssh.challenge_response_authentication }}
UsePAM {{ ssh.use_pam }}
X11Forwarding {{ ssh.x11_forwarding }}
MaxAuthTries {{ ssh.max_auth_tries }}
ClientAliveInterval {{ ssh.client_alive_interval }}
ClientAliveCountMax {{ ssh.client_alive_count_max }}
{%- if ssh.allow_users %}
AllowUsers {{ ssh.allow_users | join(' ') }}
{%- endif %}
{%- if ssh.allow_groups %}
AllowGroups {{ ssh.allow_groups | join(' ') }}
{%- endif %}
EOF

write_file "${TOP}/ssh/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Apply SSH hardening drop-in

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

${NAME}-ssh-file-directory:
  file.directory:
    - name: /etc/ssh/sshd_config.d
    - mode: '0755'
    - makedirs: True

${NAME}-ssh-file-managed:
  file.managed:
    - name: {{ sb.ssh.config_path }}
    - source: salt://{{ tplroot }}/files/sshd-security-baseline.conf.j2
    - template: jinja
    - user: root
    - group: root
    - mode: '0644'
    - defaults:
        ssh: {{ sb.ssh }}
    - require:
      - file: ${NAME}-ssh-file-directory

${NAME}-ssh-service-running:
  service.running:
    - name: {{ sb.ssh.service }}
    - enable: True
    - watch:
      - file: ${NAME}-ssh-file-managed
EOF

write_file "${TOP}/ssh/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Remove SSH hardening drop-in and reload sshd

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

${NAME}-ssh-clean-file-absent:
  file.absent:
    - name: {{ sb.ssh.config_path }}

${NAME}-ssh-clean-service-running:
  service.running:
    - name: {{ sb.ssh.service }}
    - enable: True
    - watch:
      - file: ${NAME}-ssh-clean-file-absent
EOF

write_file "${TOP}/ssh/check.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Compliance check: SSH drop-in and effective settings

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

${NAME}-ssh-check-file-exists:
  file.exists:
    - name: {{ sb.ssh.config_path }}

${NAME}-ssh-check-permit-root:
  cmd.run:
    - name: grep -Eq '^PermitRootLogin[[:space:]]+{{ sb.ssh.permit_root_login }}$' {{ sb.ssh.config_path }}
    - require:
      - file: ${NAME}-ssh-check-file-exists

${NAME}-ssh-check-password-auth:
  cmd.run:
    - name: grep -Eq '^PasswordAuthentication[[:space:]]+{{ sb.ssh.password_authentication }}$' {{ sb.ssh.config_path }}
    - require:
      - file: ${NAME}-ssh-check-file-exists

${NAME}-ssh-check-service-enabled:
  service.enabled:
    - name: {{ sb.ssh.service }}

${NAME}-ssh-check-service-running:
  service.running:
    - name: {{ sb.ssh.service }}
EOF

write_file "${TOP}/sysctl/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Apply sysctl hardening via drop-in

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- for key, value in sb.sysctl.params.items() %}
${NAME}-sysctl-present-{{ key | replace('.', '-') }}:
  sysctl.present:
    - name: {{ key }}
    - value: {{ value }}
    - config: {{ sb.sysctl.config_path }}
{%- endfor %}
EOF

write_file "${TOP}/sysctl/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Remove sysctl hardening drop-in

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

${NAME}-sysctl-clean-file-absent:
  file.absent:
    - name: {{ sb.sysctl.config_path }}

${NAME}-sysctl-clean-cmd-reload:
  cmd.run:
    - name: sysctl --system
    - onchanges:
      - file: ${NAME}-sysctl-clean-file-absent
EOF

write_file "${TOP}/sysctl/check.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Compliance check: sysctl values match policy

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

${NAME}-sysctl-check-file-exists:
  file.exists:
    - name: {{ sb.sysctl.config_path }}

{%- for key, value in sb.sysctl.params.items() %}
${NAME}-sysctl-check-{{ key | replace('.', '-') }}:
  cmd.run:
    - name: test "\$(sysctl -n {{ key }})" = "{{ value }}"
    - require:
      - file: ${NAME}-sysctl-check-file-exists
{%- endfor %}
EOF

write_file "${TOP}/services/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Stop and disable unwanted services (if unit exists)

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- for svc in sb.services.get('disabled', []) %}
{%- set sid = svc | replace('.', '-') | replace('@', '-at-') %}

${NAME}-services-dead-{{ sid }}:
  service.dead:
    - name: {{ svc }}
    - enable: False
    - onlyif:
      - systemctl list-unit-files {{ svc }} 2>/dev/null | grep -q {{ svc }}

{%- endfor %}
EOF

write_file "${TOP}/services/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Clean does not re-enable previously disabled services by default
# (would weaken security). Placeholder for explicit restore list.

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- set restore = sb.services.get('restore_on_clean', []) %}
{%- for svc in restore %}
{%- set sid = svc | replace('.', '-') | replace('@', '-at-') %}

${NAME}-services-clean-running-{{ sid }}:
  service.running:
    - name: {{ svc }}
    - enable: True
    - onlyif:
      - systemctl list-unit-files {{ svc }} 2>/dev/null | grep -q {{ svc }}

{%- endfor %}
EOF

write_file "${TOP}/services/check.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Compliance check: unwanted services are inactive/disabled when present

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- for svc in sb.services.get('disabled', []) %}
{%- set sid = svc | replace('.', '-') | replace('@', '-at-') %}

${NAME}-services-check-dead-{{ sid }}:
  cmd.run:
    - name: >
        if systemctl list-unit-files {{ svc }} 2>/dev/null | grep -q {{ svc }}; then
          systemctl is-active {{ svc }} 2>/dev/null | grep -Eq 'inactive|failed|unknown'
          && ! systemctl is-enabled {{ svc }} 2>/dev/null | grep -q enabled
        else
          true
        fi
    - shell: /bin/bash

{%- endfor %}
EOF

write_file "${TOP}/packages/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Install required packages and remove forbidden ones

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- if sb.packages.get('required') %}
${NAME}-packages-pkg-installed:
  pkg.installed:
    - pkgs:
{%- for pkg in sb.packages.required %}
      - {{ pkg }}
{%- endfor %}
{%- endif %}

{%- if sb.packages.get('forbidden') %}
${NAME}-packages-pkg-removed:
  pkg.removed:
    - pkgs:
{%- for pkg in sb.packages.forbidden %}
      - {{ pkg }}
{%- endfor %}
{%- endif %}
EOF

write_file "${TOP}/packages/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Clean: remove required packages; forbidden stay removed by default.

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- if sb.packages.get('required') %}
${NAME}-packages-clean-pkg-removed:
  pkg.removed:
    - pkgs:
{%- for pkg in sb.packages.required %}
      - {{ pkg }}
{%- endfor %}
{%- endif %}
EOF

write_file "${TOP}/packages/check.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Compliance check: required present, forbidden absent

{#- Get the \`tplroot\` from \`tpldir\` #}
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as sb with context %}

{%- for pkg in sb.packages.get('required', []) %}
${NAME}-packages-check-installed-{{ pkg | replace('.', '-') | replace('+', '-') }}:
  pkg.installed:
    - name: {{ pkg }}
{%- endfor %}

{%- for pkg in sb.packages.get('forbidden', []) %}
${NAME}-packages-check-absent-{{ pkg | replace('.', '-') | replace('+', '-') }}:
  pkg.removed:
    - name: {{ pkg }}
{%- endfor %}
EOF

write_file "docs/README.RST" <<EOF
=======================
${NAME}-formula
=======================

Linux security baseline (Debian / Ubuntu / Astra / RedHat):
SSH hardening, sysctl, services lockdown, packages policy + compliance check.

Apply::

  salt '*' state.apply ${TOP}

Check::

  salt '*' state.apply ${TOP}.check

Clean::

  salt '*' state.apply ${TOP}.clean

Pillar lookup overrides map.jinja defaults. See pillar.example.
EOF

REQUIRED=(
  "FORMULA"
  "pillar.example"
  "${TOP}/init.sls"
  "${TOP}/clean.sls"
  "${TOP}/check.sls"
  "${TOP}/map.jinja"
  "${TOP}/files/sshd-security-baseline.conf.j2"
  "${TOP}/ssh/init.sls"
  "${TOP}/ssh/clean.sls"
  "${TOP}/ssh/check.sls"
  "${TOP}/sysctl/init.sls"
  "${TOP}/sysctl/clean.sls"
  "${TOP}/sysctl/check.sls"
  "${TOP}/services/init.sls"
  "${TOP}/services/clean.sls"
  "${TOP}/services/check.sls"
  "${TOP}/packages/init.sls"
  "${TOP}/packages/clean.sls"
  "${TOP}/packages/check.sls"
  "docs/README.RST"
)

for f in "${REQUIRED[@]}"; do
  fail_if_empty "${FORMULA_DIR}/${f}"
done

grep -q "^name: ${NAME}$" "${FORMULA_DIR}/FORMULA"
grep -q 'tplroot' "${FORMULA_DIR}/${TOP}/init.sls"
grep -q 'sysctl.present\|file.managed\|service.dead\|pkg.removed' "${FORMULA_DIR}/${TOP}/sysctl/init.sls"
grep -q 'sysctl.present\|file.managed\|service.dead\|pkg.removed' "${FORMULA_DIR}/${TOP}/ssh/init.sls"

else
# --- package kind (default) ---

# --- init.sls / clean.sls ---
if [[ "${WITH_REPO}" == "true" ]]; then
  write_file "${TOP}/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
{%- if grains['os_family'] == 'Windows' %}
  - .package
{%- else %}
  - .repository
  - .package
{%- endif %}
EOF

  write_file "${TOP}/clean.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
{%- if grains['os_family'] == 'Windows' %}
  - .package.clean
{%- else %}
  - .package.clean
  - .repository.clean
{%- endif %}
EOF
else
  write_file "${TOP}/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .package
EOF

  write_file "${TOP}/clean.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .package.clean
EOF
fi

# --- package ---
write_file "${TOP}/package/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] == 'Windows' %}

{%- set win = cfg.get('windows', {}) %}
{%- set win_method = win.get('method', 'winrepo') %}
{%- set winrepo_name = win.get('winrepo_name', cfg.pkg.name) %}
{%- set choco_name = win.get('chocolatey_name', cfg.pkg.name) %}
{%- set pkg_version = cfg.pkg.get('version', '') %}

{%- if win_method == 'installer' and win.get('installer_url') %}

${NAME}-package-file-managed-installer:
  file.managed:
    - name: {{ win.installer_path }}
    - source: {{ win.installer_url }}
    - skip_verify: True
    - makedirs: True

${NAME}-package-cmd-run-installer:
  cmd.run:
    - name: '"{{ win.installer_path }}" {{ win.install_args }}'
    - require:
      - file: ${NAME}-package-file-managed-installer

{%- elif win_method == 'chocolatey' %}

${NAME}-package-chocolatey-installed:
  chocolatey.installed:
    - name: {{ choco_name }}
{%- if pkg_version %}
    - version: '{{ pkg_version }}'
{%- endif %}

{%- else %}

{# Default / winrepo: Salt Windows Software Repository #}
${NAME}-package-winrepo-pkg-installed:
  pkg.installed:
    - name: {{ winrepo_name }}
{%- if pkg_version %}
    - version: '{{ pkg_version }}'
{%- endif %}

{%- endif %}

{%- else %}

${NAME}-package-pkg-installed:
  pkg.installed:
    - name: {{ cfg.pkg.name }}
{%- if cfg.pkg.get('version') %}
    - version: '{{ cfg.pkg.version }}'
{%- endif %}
{%- if cfg.pkg.get('fromrepo') and grains['os_family'] == 'Debian' %}
    - fromrepo: {{ cfg.pkg.fromrepo }}
{%- endif %}
{%- if cfg.get('repo', {}).get('name') %}
    - require:
      - pkgrepo: ${NAME}-repository-install-pkgrepo-managed
{%- endif %}

{%- endif %}
EOF

write_file "${TOP}/package/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] == 'Windows' %}

{%- set win = cfg.get('windows', {}) %}
{%- set win_method = win.get('method', 'winrepo') %}
{%- set winrepo_name = win.get('winrepo_name', cfg.pkg.name) %}
{%- set choco_name = win.get('chocolatey_name', cfg.pkg.name) %}

{%- if win_method == 'chocolatey' %}

${NAME}-package-chocolatey-uninstalled:
  chocolatey.uninstalled:
    - name: {{ choco_name }}

{%- else %}

{# winrepo or installer cleanup via pkg.removed #}
${NAME}-package-winrepo-pkg-removed:
  pkg.removed:
    - name: {{ winrepo_name }}

{%- endif %}

{%- else %}

${NAME}-package-pkg-removed:
  pkg.removed:
    - name: {{ cfg.pkg.name }}

{%- endif %}
EOF

# --- repository (optional) ---
if [[ "${WITH_REPO}" == "true" ]]; then
  write_file "${TOP}/repository/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .install
EOF

  write_file "${TOP}/repository/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('name') %}

include:
  - .package.install
  - .key.install

{%- if grains['os_family'] == 'Debian' %}

{%- set keyring = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}
{%- set raw = cfg.repo.name %}
{%- if raw.startswith('deb ') %}
{%- set raw = raw[4:].strip() %}
{%- endif %}
{%- set comps = cfg.repo.get('comps', '') | replace(',', ' ') %}
{%- if comps and comps not in raw %}
{%- set raw = raw ~ ' ' ~ comps %}
{%- endif %}

${NAME}-repository-install-pkgrepo-managed:
  pkgrepo.managed:
    - name: deb [signed-by={{ keyring }}] {{ raw }}
    - file: {{ cfg.repo.file }}
    - humanname: {{ cfg.repo.humanname }}
    - disabled: {{ cfg.repo.disabled }}
    - require:
      - file: ${NAME}-repository-key-install-file-managed
{%- if cfg.repo.get('required_packages') %}
      - pkg: ${NAME}-repository-package-install-pkg-installed
{%- endif %}

{%- elif grains['os_family'] == 'RedHat' %}

{%- set gpg_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-install-pkgrepo-managed:
  pkgrepo.managed:
    - name: {{ cfg.repo.conf_name }}
    - humanname: {{ cfg.repo.humanname }}
    - baseurl: {{ cfg.repo.name }}
    - enabled: {{ '1' if not cfg.repo.disabled else '0' }}
    - gpgcheck: 1
    - gpgkey: file://{{ gpg_path }}
    - require:
      - file: ${NAME}-repository-key-install-file-managed

{%- endif %}

{%- endif %}
EOF

  write_file "${TOP}/repository/package/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('required_packages') %}

${NAME}-repository-package-install-pkg-installed:
  pkg.installed:
    - pkgs: {{ cfg.repo.required_packages }}

{%- endif %}
EOF

  write_file "${TOP}/repository/key/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('key_file') %}

{%- set key_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-key-install-file-managed:
  file.managed:
    - name: {{ key_path }}
    - source: {{ cfg.repo.key_file }}
    - skip_verify: True
    - makedirs: True

{%- endif %}
EOF

  write_file "${TOP}/repository/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .key.clean

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('file') %}

${NAME}-repository-clean-file-absent:
  file.absent:
    - name: {{ cfg.repo.file }}

{%- endif %}
EOF

  write_file "${TOP}/repository/key/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('key_file') %}

{%- set key_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-key-clean-file-absent:
  file.absent:
    - name: {{ key_path }}

{%- endif %}
EOF
fi

write_file "docs/README.RST" <<EOF
${NAME}
=============

Apply::

  salt '*' state.apply ${TOP}

Clean::

  salt '*' state.apply ${TOP}.clean

Pillar lookup overrides map.jinja defaults. See pillar.example.
EOF

REQUIRED=(
  "FORMULA"
  "pillar.example"
  "${TOP}/init.sls"
  "${TOP}/clean.sls"
  "${TOP}/map.jinja"
  "${TOP}/package/init.sls"
  "${TOP}/package/clean.sls"
  "docs/README.RST"
)

if [[ "${WITH_REPO}" == "true" ]]; then
  REQUIRED+=(
    "${TOP}/repository/init.sls"
    "${TOP}/repository/install.sls"
    "${TOP}/repository/clean.sls"
    "${TOP}/repository/key/install.sls"
    "${TOP}/repository/key/clean.sls"
    "${TOP}/repository/package/install.sls"
  )
fi

for f in "${REQUIRED[@]}"; do
  fail_if_empty "${FORMULA_DIR}/${f}"
done

grep -q "^name: ${NAME}$" "${FORMULA_DIR}/FORMULA"
grep -q 'tplroot' "${FORMULA_DIR}/${TOP}/init.sls"
grep -q 'pkg.installed\|chocolatey.installed' "${FORMULA_DIR}/${TOP}/package/init.sls"

fi
# end kind branch

EMPTY="$(find "${FORMULA_DIR}" -type f -empty || true)"
if [[ -n "${EMPTY}" ]]; then
  echo "ERROR: empty files found:" >&2
  echo "${EMPTY}" >&2
  exit 1
fi

echo "OK: formula created at ${FORMULA_DIR} (kind=${KIND})"
find "${FORMULA_DIR}" -type f | sort
