#!/usr/bin/env bash
# Render Salt formula from JSON spec (AI → JSON → this script → formula).
# Requires: bash, jq
#
# Usage:
#   ./render_formula.sh --spec ./spec.json [--out ./dist]
#
set -euo pipefail

SPEC=""
OUT_DIR="."

usage() {
  cat <<'USAGE'
Usage: render_formula.sh --spec <spec.json> [--out <dir>]

Reads formula JSON spec and creates <name>-formula/ with full file contents.
Requires: jq

Example:
  ./render_formula.sh --spec examples/specs/nginx.json --out /tmp
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --spec) SPEC="$2"; shift 2 ;;
    --out) OUT_DIR="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "${SPEC}" || ! -f "${SPEC}" ]]; then
  echo "ERROR: --spec file required" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required (brew install jq / apt install jq)" >&2
  exit 1
fi

if ! jq empty "${SPEC}" 2>/dev/null; then
  echo "ERROR: invalid JSON: ${SPEC}" >&2
  exit 1
fi

NAME="$(jq -r '.name // empty' "${SPEC}")"
TOP="$(jq -r '.top_level_dir // .name // empty' "${SPEC}")"
WITH_REPO="$(jq -r '(.with_repo // false) | tostring' "${SPEC}")"
RELEASE="$(jq -r '.release // 1' "${SPEC}")"
VERSION="$(date +%Y%m)"

if [[ -z "${NAME}" || -z "${TOP}" ]]; then
  echo "ERROR: name / top_level_dir required" >&2
  exit 1
fi

if [[ ! "${NAME}" =~ ^[a-zA-Z0-9_-]+$ || ! "${TOP}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "ERROR: name/top_level_dir must match [a-zA-Z0-9_-]+" >&2
  exit 1
fi

OS_COUNT="$(jq -r '(.os // []) | length' "${SPEC}")"
OSF_COUNT="$(jq -r '(.os_family // []) | length' "${SPEC}")"
if [[ "${OS_COUNT}" -lt 1 || "${OSF_COUNT}" -lt 1 ]]; then
  echo "ERROR: os and os_family must be non-empty arrays" >&2
  exit 1
fi

FORMULA_DIR="${OUT_DIR}/${TOP}-formula"
mkdir -p "${FORMULA_DIR}"

write_file() {
  local rel="$1"
  local target="${FORMULA_DIR}/${rel}"
  mkdir -p "$(dirname "${target}")"
  cat > "${target}"
}

fail_if_empty() {
  local f="$1"
  [[ -s "${f}" ]] || { echo "ERROR: empty file: ${f}" >&2; exit 1; }
}

# --- FORMULA ---
write_file "FORMULA" <<EOF
name: ${NAME}
os:
$(jq -r '.os[] | "  - \(.)"' "${SPEC}")
os_family:
$(jq -r '.os_family[] | "  - \(.)"' "${SPEC}")
version: ${VERSION}
release: ${RELEASE}
summary: $(jq -r '.summary // "Autogenerated formula" | @json' "${SPEC}")
description: $(jq -r '.description // .summary // "Autogenerated Salt formula" | @json' "${SPEC}")
top_level_dir: ${TOP}
EOF

# --- pillar.example (JSON under lookup is valid and readable) ---
write_file "pillar.example" <<EOF
${NAME}:
  # Override map.jinja defaults
  lookup: $(jq -c '.pillar_lookup // {}' "${SPEC}")
EOF

# --- map.jinja ---
write_file "${TOP}/map.jinja" <<EOF
{# -*- coding: utf-8 -*- #}
{# vim: ft=jinja #}
{# Generated by render_formula.sh from JSON spec #}
{% set mapdata = salt['grains.filter_by']($(jq -c '.map_defaults // {"default":{}}' "${SPEC}"), merge=salt['pillar.get']('${NAME}:lookup'), base='default') %}
EOF

# --- init.sls / clean.sls ---
if [[ "${WITH_REPO}" == "true" ]]; then
  write_file "${TOP}/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
{%- if grains['os_family'] == 'Windows' %}
  - .package
{%- else %}
  - .repository
  - .package
{%- endif %}
EOF

  write_file "${TOP}/clean.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
{%- if grains['os_family'] == 'Windows' %}
  - .package.clean
{%- else %}
  - .package.clean
  - .repository.clean
{%- endif %}
EOF
else
  write_file "${TOP}/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .package
EOF

  write_file "${TOP}/clean.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .package.clean
EOF
fi

# --- package ---
write_file "${TOP}/package/init.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] == 'Windows' %}

{%- set win = cfg.get('windows', {}) %}
{%- set win_method = win.get('method', 'winrepo') %}
{%- set winrepo_name = win.get('winrepo_name', cfg.pkg.name) %}
{%- set choco_name = win.get('chocolatey_name', cfg.pkg.name) %}
{%- set pkg_version = cfg.pkg.get('version', '') %}

{%- if win_method == 'installer' and win.get('installer_url') %}

${NAME}-package-file-managed-installer:
  file.managed:
    - name: {{ win.installer_path }}
    - source: {{ win.installer_url }}
    - skip_verify: True
    - makedirs: True

${NAME}-package-cmd-run-installer:
  cmd.run:
    - name: '"{{ win.installer_path }}" {{ win.install_args }}'
    - require:
      - file: ${NAME}-package-file-managed-installer

{%- elif win_method == 'chocolatey' %}

${NAME}-package-chocolatey-installed:
  chocolatey.installed:
    - name: {{ choco_name }}
{%- if pkg_version %}
    - version: '{{ pkg_version }}'
{%- endif %}

{%- else %}

{# Default / winrepo: Salt Windows Software Repository #}
${NAME}-package-winrepo-pkg-installed:
  pkg.installed:
    - name: {{ winrepo_name }}
{%- if pkg_version %}
    - version: '{{ pkg_version }}'
{%- endif %}

{%- endif %}

{%- else %}

${NAME}-package-pkg-installed:
  pkg.installed:
    - name: {{ cfg.pkg.name }}
{%- if cfg.pkg.get('version') %}
    - version: '{{ cfg.pkg.version }}'
{%- endif %}
{%- if cfg.pkg.get('fromrepo') and grains['os_family'] == 'Debian' %}
    - fromrepo: {{ cfg.pkg.fromrepo }}
{%- endif %}
{%- if cfg.get('repo', {}).get('name') %}
    - require:
      - pkgrepo: ${NAME}-repository-install-pkgrepo-managed
{%- endif %}

{%- endif %}
EOF

write_file "${TOP}/package/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] == 'Windows' %}

{%- set win = cfg.get('windows', {}) %}
{%- set win_method = win.get('method', 'winrepo') %}
{%- set winrepo_name = win.get('winrepo_name', cfg.pkg.name) %}
{%- set choco_name = win.get('chocolatey_name', cfg.pkg.name) %}

{%- if win_method == 'chocolatey' %}

${NAME}-package-chocolatey-uninstalled:
  chocolatey.uninstalled:
    - name: {{ choco_name }}

{%- else %}

{# winrepo or installer cleanup via pkg.removed #}
${NAME}-package-winrepo-pkg-removed:
  pkg.removed:
    - name: {{ winrepo_name }}

{%- endif %}

{%- else %}

${NAME}-package-pkg-removed:
  pkg.removed:
    - name: {{ cfg.pkg.name }}

{%- endif %}
EOF

# --- repository (optional) ---
if [[ "${WITH_REPO}" == "true" ]]; then
  write_file "${TOP}/repository/init.sls" <<'EOF'
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .install
EOF

  write_file "${TOP}/repository/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('name') %}

include:
  - .package.install
  - .key.install

{%- if grains['os_family'] == 'Debian' %}

{%- set keyring = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}
{%- set raw = cfg.repo.name %}
{%- if raw.startswith('deb ') %}
{%- set raw = raw[4:].strip() %}
{%- endif %}
{%- set comps = cfg.repo.get('comps', '') | replace(',', ' ') %}
{%- if comps and comps not in raw %}
{%- set raw = raw ~ ' ' ~ comps %}
{%- endif %}

${NAME}-repository-install-pkgrepo-managed:
  pkgrepo.managed:
    - name: deb [signed-by={{ keyring }}] {{ raw }}
    - file: {{ cfg.repo.file }}
    - humanname: {{ cfg.repo.humanname }}
    - disabled: {{ cfg.repo.disabled }}
    - require:
      - file: ${NAME}-repository-key-install-file-managed
{%- if cfg.repo.get('required_packages') %}
      - pkg: ${NAME}-repository-package-install-pkg-installed
{%- endif %}

{%- elif grains['os_family'] == 'RedHat' %}

{%- set gpg_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-install-pkgrepo-managed:
  pkgrepo.managed:
    - name: {{ cfg.repo.conf_name }}
    - humanname: {{ cfg.repo.humanname }}
    - baseurl: {{ cfg.repo.name }}
    - enabled: {{ '1' if not cfg.repo.disabled else '0' }}
    - gpgcheck: 1
    - gpgkey: file://{{ gpg_path }}
    - require:
      - file: ${NAME}-repository-key-install-file-managed

{%- endif %}

{%- endif %}
EOF

  write_file "${TOP}/repository/package/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('required_packages') %}

${NAME}-repository-package-install-pkg-installed:
  pkg.installed:
    - pkgs: {{ cfg.repo.required_packages }}

{%- endif %}
EOF

  write_file "${TOP}/repository/key/install.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('key_file') %}

{%- set key_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-key-install-file-managed:
  file.managed:
    - name: {{ key_path }}
    - source: {{ cfg.repo.key_file }}
    - skip_verify: True
    - makedirs: True

{%- endif %}
EOF

  write_file "${TOP}/repository/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

include:
  - .key.clean

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('file') %}

${NAME}-repository-clean-file-absent:
  file.absent:
    - name: {{ cfg.repo.file }}

{%- endif %}
EOF

  write_file "${TOP}/repository/key/clean.sls" <<EOF
# -*- coding: utf-8 -*-
# vim: ft=sls
{%- set tplroot = tpldir.split('/')[0] %}
{%- from tplroot ~ "/map.jinja" import mapdata as cfg with context %}

{%- if grains['os_family'] != 'Windows' and cfg.repo.get('key_file') %}

{%- set key_path = cfg.repo.key_keyrings_dir.rstrip('/') ~ '/' ~ cfg.repo.conf_name ~ '.gpg' %}

${NAME}-repository-key-clean-file-absent:
  file.absent:
    - name: {{ key_path }}

{%- endif %}
EOF
fi

# --- docs ---
write_file "docs/README.RST" <<EOF
${NAME}
=============

Apply::

  salt '*' state.apply ${TOP}

Clean::

  salt '*' state.apply ${TOP}.clean

Pillar lookup overrides map.jinja defaults. See pillar.example.
EOF

# --- self-check ---
REQUIRED=(
  "FORMULA"
  "pillar.example"
  "${TOP}/init.sls"
  "${TOP}/clean.sls"
  "${TOP}/map.jinja"
  "${TOP}/package/init.sls"
  "${TOP}/package/clean.sls"
  "docs/README.RST"
)

if [[ "${WITH_REPO}" == "true" ]]; then
  REQUIRED+=(
    "${TOP}/repository/init.sls"
    "${TOP}/repository/install.sls"
    "${TOP}/repository/clean.sls"
    "${TOP}/repository/key/install.sls"
    "${TOP}/repository/key/clean.sls"
    "${TOP}/repository/package/install.sls"
  )
fi

for f in "${REQUIRED[@]}"; do
  fail_if_empty "${FORMULA_DIR}/${f}"
done

grep -q "^name: ${NAME}$" "${FORMULA_DIR}/FORMULA"
grep -q 'tplroot' "${FORMULA_DIR}/${TOP}/init.sls"
grep -q 'pkg.installed\|chocolatey.installed' "${FORMULA_DIR}/${TOP}/package/init.sls"

EMPTY="$(find "${FORMULA_DIR}" -type f -empty || true)"
if [[ -n "${EMPTY}" ]]; then
  echo "ERROR: empty files found:" >&2
  echo "${EMPTY}" >&2
  exit 1
fi

echo "OK: formula created at ${FORMULA_DIR}"
find "${FORMULA_DIR}" -type f | sort
